apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: megarantis-server-deployment
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: megarantis-server
  strategy: 
    type: RollingUpdate
  template: 
    metadata:
      labels:
        app: megarantis-server
    spec:
      containers: 
      - name: mega-server
        image: sitnarim/megarantis-server
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: megarantis-server-service
  labels: 
    app: mega-server-service
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: megarantis-server

---
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: megarantis-db-deployment
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: megarantis-db 
  strategy: 
    type: RollingUpdate
  template: 
    metadata:
      labels:
        app: megarantis-db
    spec:
      containers: 
      - name: mega-db
        image: sitnarim/megarantis-db
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata: 
  name: megarantis-db-service
  labels:
    app: mega-db-service
spec:
  type: NodePort
  ports: 
  - port: 6379
    protocol: TCP
  selector: 
    app: megarantis-db

 
